#!/usr/bin/env bash
# Dotfiles manifest - single source of truth for repos, symlinks, and directories

# ── Managed-root ROLES (what dotfiles knows about each root it touches) ───────
# Dotfiles is the transport layer; every root it manages has exactly one role:
#   active-repo      synced by sync (REPOS): pull/push/commit each run
#   archive-repo     legacy, NOT synced (ARCHIVED_REPOS): kept for reference only
#   external-managed forked upstream, security-gated sync (AGENT_SKILLS_DIR)
#   generated-target written by dotfiles, never hand-edited (COMBINED_RULES_TARGETS,
#                    PROJECT_SKILLS_TARGETS, codex prompts / gemini commands)
#   artifact-dir     ensured to exist, content owned by the user (DIRECTORIES)
# An archived root must NEVER appear in an active list, or it resurrects stale generated
# affordances (e.g. the dangling it-worker-* skill links). See INVARIANTS.md.

# Active repos to clone/sync: "remote|target_path" (role: active-repo)
REPOS=(
  "git@github:MGallo-Code/EA.git|~/Documents/EA"
  "git@github:MGallo-Code/NVIM-Setup.git|~/.config/nvim"
  "git@github:MGallo-Code/Wiki.git|~/Documents/Wiki"
  "git@github:MGallo-Code/Notes.git|~/Documents/Notes"
)

# Archived repos: "remote|target_path" (role: archive-repo). NEVER synced; a tombstone for a
# root kept locally but inactive. Currently EMPTY: IT-Worker's local copy was removed
# 2026-06-19 (archive lives at MGallo-Code/IT-Worker on GitHub; its bulky client artifacts are
# in ~/Documents/Customer-Work). Re-add an entry if a repo is ever archived-but-kept-local.
ARCHIVED_REPOS=()

# EA-only repos (skipped with --dev) - subset of active REPOS above
EA_REPOS=(
  "git@github:MGallo-Code/EA.git|~/Documents/EA"
  "git@github:MGallo-Code/Wiki.git|~/Documents/Wiki"
  "git@github:MGallo-Code/Notes.git|~/Documents/Notes"
)

# Symlinks to create: "source|target"
# Claude loads a whole DIRECTORY of rules, so a dir symlink covers every rule file.
SYMLINKS=(
  "~/Documents/EA/claude-config/global-rules|~/.claude/rules"
  "~/Documents/EA/claude-config/global-hooks|~/.claude/hooks"
  # global-agents -> ~/.claude/agents: Claude subagent defs (e.g. human-voice). Claude-ONLY -
  # codex/gemini have no subagent concept, so there is NO codex/gemini target (a SYMLINKS entry
  # only ever lands in ~/.claude). Previously hand-linked by EA/claude-config/link.sh (now
  # retired); managed here so the wiring is reproducible. (parity: manifest.ps1 + INV-2 token)
  "~/Documents/EA/claude-config/global-agents|~/.claude/agents"
)

# Combined global rules for single-file agent tools.
# Codex and Gemini each load ONE global instruction file (AGENTS.md / GEMINI.md),
# not a directory. You can't symlink a dir into a file, so we GENERATE that file by
# concatenating every global-rules/*.md - one source of truth, three consumers.
# (agent-skills.md is one of those files, so the skills nudge is still included.)
# Regenerated by setup.sh and sync.sh; never hand-edit the generated targets
# (they are chmod 0444 read-only so an edit fails fast - edit the source rules).
#
# NEW-AGENT EXTENSION POINT: to make the kit the default for another agent (DeepSeek,
# or any future tool), add TWO lines: its single-file rules path here, and its skills
# dir to AGENT_SKILLS_TARGETS below. That is the entire wiring. Only add a target whose
# config dir actually EXISTS on disk - a path to a non-existent ~/.<agent> is dead
# config (e.g. ~/.deepseek does not exist today, so it is documented here, not wired).
GLOBAL_RULES_DIR="~/Documents/EA/claude-config/global-rules"
COMBINED_RULES_TARGETS=(
  "~/.codex/AGENTS.md"
  "~/.gemini/GEMINI.md"
)

# Concatenate all global-rules/*.md into each single-file target. Idempotent;
# replaces a prior symlink with a generated file. Written to be safe under `set -e`.
# Relies on expand()/ok()/warn() from the sourcing script (setup.sh / sync.sh).
regen_combined_agent_rules() {
    local src; src="$(expand "$GLOBAL_RULES_DIR")"
    if [ ! -d "$src" ]; then warn "combined-rules: no global-rules dir at $src"; return 0; fi
    local tmp; tmp="$(mktemp)"
    printf '%s\n\n' "<!-- AUTO-GENERATED by dotfiles from $GLOBAL_RULES_DIR. Edit the source rule files, not this copy. -->" > "$tmp"
    local f
    for f in "$src"/*.md; do
        [ -f "$f" ] || continue
        cat "$f" >> "$tmp"
        printf '\n\n' >> "$tmp"
    done
    local tgt expanded
    for tgt in "${COMBINED_RULES_TARGETS[@]}"; do
        expanded="$(expand "$tgt")"
        mkdir -p "$(dirname "$expanded")"
        if [ -L "$expanded" ]; then rm -f "$expanded"; fi
        # Diff-guard: these targets are GENERATED from $GLOBAL_RULES_DIR. If a real
        # file is already here and differs from what we're about to write, someone
        # hand-edited the copy (its edits would be silently lost on this sync), so
        # back it up first. Edit the SOURCE rule files, never this generated copy.
        if [ -f "$expanded" ] && ! cmp -s "$tmp" "$expanded"; then
            cp -p "$expanded" "$expanded.sync-backup" 2>/dev/null || true
            warn "combined-rules: $tgt differed from source; backed up to $tgt.sync-backup before regenerating (edit the global-rules source, not this copy)"
        fi
        # A prior run left it 0444 (below); re-grant write so cp can overwrite it.
        [ -f "$expanded" ] && chmod u+w "$expanded" 2>/dev/null || true
        cp "$tmp" "$expanded"
        # chmod 0444: OS-enforced read-only so an agent's Edit fails fast with EACCES
        # (unlike the unreliable PreToolUse Write/Edit block). The cheapest reliable
        # enforcer in the kit: it makes "edit the source, not the generated copy"
        # mechanically true, not just advice. Sync re-grants write above each regen.
        chmod 0444 "$expanded"
        ok "combined-rules: generated $tgt (read-only; edit the global-rules source)"
    done
    rm -f "$tmp"
}

# ── Forked agent-skills (addyosmani/agent-skills) ────────────────────
# Two remotes: origin = your fork (MGallo-Code/agent-skills, trusted, push),
# upstream = Addy (untrusted source of truth, gated pull). Synced by the
# dedicated, security-gated sync_skills_repo() in sync.sh, NOT the generic
# sync_repo (which would blind ff-pull origin and skip the gate). Kept OUT of
# REPOS for that reason.
AGENT_SKILLS_DIR="~/Documents/agent-skills"
AGENT_SKILLS_UPSTREAM="https://github.com/addyosmani/agent-skills.git"

# Each tool reads global skills from its own dir; sync symlinks every
# skills/<name> from the vendor repo into each (idempotent, never clobbers
# existing real skill dirs like calendar/contact/dev-update).
AGENT_SKILLS_TARGETS=(
  "~/.claude/skills"
  "~/.codex/skills"
  "~/.gemini/skills"
)

# ── MCP host identity (ADR-0002 / remote-hubs): the one machine that serves hubs ──
# The HOST is exactly ONE machine that runs the MCP hubs and serves them over Tailscale
# (courier today; calendar/nexus as they are remoted). Mac-only: courier needs the macOS
# *login* keychain (14 account passwords in a logged-in GUI session) + the ~/Mail maildir +
# notmuch index; nexus needs the macOS chat.db. Every OTHER machine is a CLIENT that reaches
# the hubs over Tailscale. "MCP host" is a ROLE keyed on this ONE variable: migrating to the
# planned always-on Mac mini is "change MCP_HOST, run the host bootstrap there" - nothing else
# moves. (Was MAIL_HOST when courier was the only remoted hub; generalized in remote-hubs Phase B.)
#
# MCP_HOST is the Tailscale MagicDNS *host label* (lowercase, hyphenated). It is NOT `hostname`
# (which on this Mac is "MacBookPro") - it is derived from macOS LocalHostName
# ("Michaels-MacBook-Pro" -> lowercased). Host self-detection (is_mcp_host) normalizes
# LocalHostName and compares to this; setup + hub-host-bootstrap then assert host capability and
# FAIL LOUD rather than silently wiring a host as a client (ADR-0002 review finding).
MCP_HOST="michaels-macbook-pro"
TAILNET="tail7a0764.ts.net"
COURIER_HTTP_PORT="8765"
# courier client URL: TLS terminated by `tailscale serve` on the host, stable MagicDNS name.
COURIER_REMOTE_URL="https://${MCP_HOST}.${TAILNET}/mcp"
# Mandatory bearer token: ONE mode-600 file per machine, OUTSIDE any repo (never in
# git; secret-scan-gated). Consumed via the COURIER_BEARER env var - NEVER passed on a
# command line (would leak to the process table) and never inlined into a CLI's stored
# config. See ADR-0002 "As-built" + the cross-check review.
COURIER_TOKEN_FILE="~/.config/courier/auth-token"

# calendar (cloud Google-API hub; remoted in remote-hubs Phase C). Role-aware exactly like courier:
# host stdio on the MCP host, http+bearer client elsewhere, fronted by `tailscale serve --set-path
# /calendar`. Its OWN per-hub bearer (${CALENDAR_BEARER}) + mode-600 token file - NEVER shared with
# courier (one leak must not expose two hubs). Port + serve/mcp paths are sole-sourced in hubs.json.
CALENDAR_REMOTE_URL="https://${MCP_HOST}.${TAILNET}/calendar/mcp"
CALENDAR_TOKEN_FILE="~/.config/calendar/auth-token"

# ── Custom global skills (tracked in EA) ─────────────────────────────
# Custom skills authored in EA (calendar, contact, dev-update, forge), linked into all 3
# agents alongside the vendor agent-skills, into the SAME AGENT_SKILLS_TARGETS dirs.
# Linked by sync's regen_agent_skills_links (idempotent; never clobbers real dirs).
GLOBAL_SKILLS_DIR="~/Documents/EA/claude-config/global-skills"

# ── Project (repo-scoped) skills -> codex/gemini, namespaced ──────────
# Claude reads each repo's .claude/skills/* project-scoped already. codex/gemini have
# no project-skill scope, so we link them GLOBALLY, namespaced "<label>-<skill>" to
# avoid collisions (EA and Wiki BOTH define `refresh`). "label|skills_dir".
PROJECT_SKILLS=(
  "ea|~/Documents/EA/.claude/skills"
  "wiki|~/Documents/Wiki/.claude/skills"
  "sbic|~/Documents/SBIC/.claude/skills"
)
# Archived project skills (role: archive-project-skills). Currently EMPTY: IT-Worker's skills
# went with its local copy (removed 2026-06-19). sync's stale-skill cleanup +
# scripts/ci/check-skill-targets.py still guard against any dangling generated skill link.
ARCHIVED_PROJECT_SKILLS=()
# codex + gemini global skills dirs (AGENT_SKILLS_TARGETS minus Claude - Claude keeps
# the un-namespaced project-scoped originals).
PROJECT_SKILLS_TARGETS=(
  "~/.codex/skills"
  "~/.gemini/skills"
)

# ── Claude slash-commands -> codex prompts + gemini TOML ──────────────
# Source of truth stays the tracked Claude `.md`. sync regenerates a per-tool copy
# into ~/.codex/prompts/*.md and ~/.gemini/commands/*.toml (different formats).
# "prefix|commands_dir" - empty prefix = bare name; "sbic" = sbic-<name>.
COMMAND_SOURCES=(
  "|~/Documents/EA/claude-config/global-commands"
  "sbic|~/Documents/SBIC/.claude/commands"
)

# Directories to ensure exist
DIRECTORIES=(
  "~/Documents/Learning"
  "~/Documents/Jobs"
)

# Shell command files (relative to dotfiles repo root)
SHELL_CORE="shell/core.zsh"
SHELL_EA="shell/ea.zsh"

# ── Per-ROLE hub MCP wiring (shared by setup.sh AND sync.sh) ──────────
# Defined here - sourced by BOTH - so the host-vs-client decision AND every hub `mcp add`
# live in ONE place. (The ADR-0002 review caught setup.sh and sync.sh each owning a separate
# copy, with the repeatable `sync` silently re-wiring courier as broken local stdio on clients;
# Phase A of the remote-hubs plan generalized that single courier function into the hub
# primitives below so the same guard covers EVERY hub - dotfiles INV-5, enforced by
# scripts/ci/check-hub-wiring.py.) These functions use expand/ok/warn (from the sourcing script)
# and the per-server PATH/SRC vars (NEXUS_SERVER, COURIER_PATH/SRC, DOCGEN_PATH/SRC,
# DOCGEN_BROWSERS, CALENDAR_PATH/SRC, COURIER_REMOTE_URL; set in each script's MCP section),
# resolved lazily at call time.

# True iff THIS machine is the MCP host (the box that runs + serves the hubs). Keys on the STABLE
# macOS LocalHostName normalized to the MagicDNS label, NOT `hostname` (which is "MacBookPro" here);
# Mac-only by definition (returns 1 off Darwin before scutil is ever called). This is the CAPABILITY
# predicate - it drives the per-hub host/client WIRING below (a box wires courier host-stdio iff it
# CAN be the host). The host/client ROLE (intent: --host/--client) is a separate, flag-overridable
# decision made in setup.sh; the fail-loud guards live in setup.sh + scripts/hub-host-bootstrap.sh.
is_mcp_host() {
    [ "$(uname -s)" = "Darwin" ] || return 1
    local lh; lh="$(scutil --get LocalHostName 2>/dev/null | tr '[:upper:]' '[:lower:]')"
    [ "$lh" = "$MCP_HOST" ]
}

# stdio add for one hub on one CLI (host/local role; no token). Per-hub env flags + exec command
# are literal arrays (NOT a word-split string). The `--` exec separator is cli-specific:
# claude/codex take it, gemini does NOT. Empty arrays use the bash-3.2 `set -u`-safe
# `"${a[@]+"${a[@]}"}"` idiom - macOS ships bash 3.2, where a bare "${a[@]}" on an EMPTY array
# aborts under set -u.
_hub_stdio_add() {
    local cli="$1" name="$2"
    local -a envs=() exec_cmd=()
    case "$name" in
        nexus)    exec_cmd=(node "$NEXUS_SERVER") ;;
        courier)  envs=(--env "PYTHONPATH=$COURIER_SRC")
                  exec_cmd=(uv run --project "$COURIER_PATH" --no-sync python -m courier.server) ;;
        docgen)   envs=(--env "PYTHONPATH=$DOCGEN_SRC" --env "PLAYWRIGHT_BROWSERS_PATH=$DOCGEN_BROWSERS")
                  exec_cmd=(uv run --project "$DOCGEN_PATH" --no-sync python -m docgen.server) ;;
        calendar) envs=(--env "PYTHONPATH=$CALENDAR_SRC")
                  exec_cmd=(uv run --project "$CALENDAR_PATH" --no-sync python -m ea_calendar.server) ;;
        *) warn "_hub_stdio_add: unknown hub '$name'"; return 1 ;;
    esac
    case "$cli" in
        claude) "$cli" mcp add --scope=user "$name" "${envs[@]+"${envs[@]}"}" -- "${exec_cmd[@]}" >/dev/null ;;
        codex)  "$cli" mcp add "$name" "${envs[@]+"${envs[@]}"}" -- "${exec_cmd[@]}" >/dev/null ;;
        gemini) "$cli" mcp add --scope user "$name" "${envs[@]+"${envs[@]}"}" "${exec_cmd[@]}" >/dev/null ;;
    esac
}

# http client add for one hub on one CLI (client role). GENERIC over (url, token_env): the bearer is
# referenced ONLY as the ${<token_env>} env var in the wiring SOURCE, never a literal token (dotfiles
# INV-4). The inline `\${$token_env}` expands to e.g. ${COURIER_BEARER} in the argv. claude/codex
# store that REFERENCE and resolve it at launch (codex via --bearer-token-env-var). gemini is the
# exception: on WSL/Linux it MATERIALIZES the reference into ~/.gemini/settings.json at add-time (the
# COURIER_BEARER value is in the env there, so the real token lands at-rest in the config; on macOS
# this box stores the ref, so it is platform-dependent). So after the gemini add we re-lock that file
# 0600 (the materialized token is never group/world-readable), and check-hub-wiring.py --host
# (host-side) flags any literal so the token can be ROTATED. See gemini_relock_settings.
_hub_http_add() {
    local cli="$1" name="$2" url="$3" token_env="$4"
    case "$cli" in
        claude) "$cli" mcp add --scope=user --transport http "$name" "$url" --header "Authorization: Bearer \${$token_env}" >/dev/null ;;
        gemini) "$cli" mcp add --scope user --transport http -H "Authorization: Bearer \${$token_env}" "$name" "$url" >/dev/null
                gemini_relock_settings ;;
        codex)  "$cli" mcp add "$name" --url "$url" --bearer-token-env-var "$token_env" >/dev/null ;;
    esac
}

# INV-4 defense: re-lock ~/.gemini/settings.json to 0600 right after a gemini http add, because gemini
# may materialize the bearer REFERENCE into the file (verified on WSL). Idempotent + EOF/`set -e`-safe.
gemini_relock_settings() {
    local gs="$HOME/.gemini/settings.json"
    [ -f "$gs" ] && chmod 600 "$gs" 2>/dev/null || true
}

# Wire ONE hub for THIS machine's role, for one CLI (the per-hub primitive; folds the old
# register_courier_mcp). role=host -> stdio; role=client -> http+bearer.
register_hub_mcp() {
    local cli="$1" name="$2" role="$3" url="${4:-}" token_env="${5:-}"
    case "$role" in
        host)   _hub_stdio_add "$cli" "$name" ;;
        client) _hub_http_add "$cli" "$name" "$url" "$token_env" ;;
        *) warn "register_hub_mcp: unknown role '$role' for $name"; return 1 ;;
    esac
}

# Wire ALL global hubs for one CLI - the dedup'd replacement for the old register_global_mcp that
# setup.sh and sync.sh each carried byte-identically. Idempotent (remove-then-add); courier is the
# only role-aware hub (host stdio on the MCP host, http+bearer elsewhere), the rest are always
# local stdio. EVERY hub `mcp add` lives HERE, so check-hub-wiring (INV-5) can prove no setup/sync
# script wires a hub directly.
register_all_hub_mcp() {
    local cli="$1"
    command -v "$cli" >/dev/null 2>&1 || { warn "$cli not found - skipping its global MCP wiring"; return; }
    local name scope_flag=""
    if [ "$cli" = "codex" ]; then
        # codex keeps MCP servers in config.toml; `codex mcp remove` can't run when that file
        # won't parse (a drifted-version entry with an invalid transport), which deadlocks
        # re-wiring. Text-strip the managed blocks first so codex can always load, then re-add.
        perl -0pi -e '
            s/^\[mcp_servers\.(?:nexus|courier|docgen|calendar)(?:\.[^\]]*)?\][^\n]*\n(?:(?!^\[)[^\n]*\n?)*//mg;
            s/\n{3,}/\n\n/g;
        ' "$HOME/.codex/config.toml" 2>/dev/null || true
    else
        case "$cli" in claude) scope_flag="--scope=user" ;; gemini) scope_flag="--scope user" ;; esac
        for name in nexus courier docgen calendar; do "$cli" mcp remove $scope_flag "$name" >/dev/null 2>&1; done
    fi
    register_hub_mcp "$cli" nexus host
    register_hub_mcp "$cli" docgen host
    # Role-aware HTTP-served hubs (hubs.json): host stdio on the MCP host, http+bearer client
    # elsewhere. Each carries its OWN per-hub bearer + mode-600 token, never shared. courier (Phase A)
    # + calendar (Phase C). A Linux/WSL client (is_mcp_host false) wires both as http clients.
    if is_mcp_host; then
        register_hub_mcp "$cli" courier  host
        register_hub_mcp "$cli" calendar host
    else
        register_hub_mcp "$cli" courier  client "$COURIER_REMOTE_URL"  COURIER_BEARER
        register_hub_mcp "$cli" calendar client "$CALENDAR_REMOTE_URL" CALENDAR_BEARER
    fi
    ok "$cli: global MCP wired (nexus + courier + docgen + calendar)"
}

# HOST only: stand up / refresh one LaunchAgent + `tailscale serve` per HTTP-served hub in the
# registry (hubs.json). Idempotent + re-runnable. Reads hubs.json with jq (present on macOS, the
# only host). The caller guards is_mcp_host; this guards a missing registry/jq/bootstrap so a
# host without them degrades to a warn, never a hard abort under `set -e`.
bootstrap_all_hubs() {
    local hubs_json="$1" bootstrap="$2"
    if [ ! -f "$hubs_json" ]; then warn "hub bootstrap: $hubs_json not found - skipping"; return 0; fi
    if ! command -v jq >/dev/null 2>&1; then warn "hub bootstrap: jq not found - skipping"; return 0; fi
    if [ ! -x "$bootstrap" ]; then warn "hub bootstrap: $bootstrap not executable - skipping"; return 0; fi
    local hub name port run token serve mcp
    jq -c '.[]' "$hubs_json" | while IFS= read -r hub; do
        [ -n "$hub" ] || continue
        name="$(printf '%s' "$hub"  | jq -r '.name')"
        port="$(printf '%s' "$hub"  | jq -r '.port')"
        run="$(printf '%s' "$hub"   | jq -r '.run_cmd')"
        token="$(printf '%s' "$hub" | jq -r '.token_file')"
        serve="$(printf '%s' "$hub" | jq -r '.serve_path')"
        mcp="$(printf '%s' "$hub"   | jq -r '.mcp_path')"
        "$bootstrap" "$name" "$port" "$run" "$token" "$serve" "$mcp" \
            || warn "hub host bootstrap ($name) reported an issue - see output above"
    done
    return 0
}

# CLIENT-only: ensure ONE hub's mode-600 bearer file exists (prompt-paste once - ADR-0002 token
# decision (a)). GENERIC over (display name, token file, env-var name) so every role-aware hub reuses
# it; per-hub tokens, never shared. EOF-safe under `set -e` (read || true), so a non-TTY/piped run
# does not abort here. The <HUB>_BEARER env export itself lives in shell/ea.zsh.
provision_hub_client_token() {
    local name="$1" token_path="$2" bearer_var="$3"
    local tf; tf="$(expand "$token_path")"
    mkdir -p "$(dirname "$tf")"; chmod 700 "$(dirname "$tf")" 2>/dev/null || true
    if [ -s "$tf" ]; then chmod 600 "$tf"; ok "$name client token present ($tf)"; return; fi
    warn "$name client needs the bearer token from the MCP host ($MCP_HOST)."
    warn "On the host run:  cat $token_path   then paste it here."
    printf "  Paste %s token (hidden; empty to skip): " "$name"
    local tok=""; read -rs tok || true; echo
    if [ -n "$tok" ]; then
        ( umask 177; printf '%s' "$tok" > "$tf" ); chmod 600 "$tf"
        ok "$name token saved ($tf, mode 600). Open a new shell to export $bearer_var."
    else
        warn "no token entered - $name client will 401 until $tf exists."
    fi
}

# CLIENT-only: provision EVERY role-aware hub's bearer token in one pass (one paste per hub).
provision_all_client_tokens() {
    provision_hub_client_token courier  "$COURIER_TOKEN_FILE"  COURIER_BEARER
    provision_hub_client_token calendar "$CALENDAR_TOKEN_FILE" CALENDAR_BEARER
}
