# Dotfiles manifest - Windows (mirrors manifest.sh)

$Repos = @(
    @{ Remote = "git@github:MGallo-Code/EA.git";         Target = "$HOME\Documents\EA" }
    @{ Remote = "git@github:MGallo-Code/NVIM-Setup.git";  Target = "$env:LOCALAPPDATA\nvim" }
    @{ Remote = "git@github:MGallo-Code/Wiki.git";        Target = "$HOME\Documents\Wiki" }
    @{ Remote = "git@github:MGallo-Code/Notes.git";       Target = "$HOME\Documents\Notes" }
    @{ Remote = "git@github:MGallo-Code/IT-Worker.git";   Target = "$HOME\Documents\IT-Worker" }
)

$EARepos = @(
    "EA"
    "Wiki"
    "Notes"
    "IT-Worker"
)

$Symlinks = @(
    @{ Source = "$HOME\Documents\EA\claude-config\global-rules"; Target = "$HOME\.claude\rules" }
    # Mirror of manifest.sh: wire the global-hooks dir so hook scripts (notify,
    # stacked-push guard) are available on Windows too. Without this, ~/.claude/hooks
    # never exists on Windows. (parity-checked: scripts/ci/check-parity.py)
    @{ Source = "$HOME\Documents\EA\claude-config\global-hooks"; Target = "$HOME\.claude\hooks" }
)

# Codex and Gemini each load ONE global instruction file. Mirror of manifest.sh:
# instead of symlinking only agent-skills.md, GENERATE a combined file from ALL
# global-rules/*.md so Windows agents get the FULL ruleset, not a subset. Generated by
# Regen-CombinedAgentRules in setup.ps1. (parity-checked: scripts/ci/check-parity.py)
$GlobalRulesDir = "$HOME\Documents\EA\claude-config\global-rules"
$CombinedRulesTargets = @(
    "$HOME\.codex\AGENTS.md"
    "$HOME\.gemini\GEMINI.md"
)

# ── Forked agent-skills (addyosmani/agent-skills) ────────────────────
# Two remotes: origin = your fork (trusted, push), upstream = Addy (untrusted,
# gated pull). Synced by the dedicated, security-gated Sync-SkillsRepo in
# sync.ps1, NOT the generic Sync-Repo. Kept OUT of $Repos for that reason.
$AgentSkillsDir = "$HOME\Documents\agent-skills"
$AgentSkillsUpstream = "https://github.com/addyosmani/agent-skills.git"

# Each tool reads global skills from its own dir; sync symlinks every
# skills\<name> from the vendor repo into each (idempotent, never clobbers
# existing real skill dirs like calendar/contact/dev-update).
$AgentSkillsTargets = @(
    "$HOME\.claude\skills"
    "$HOME\.codex\skills"
    "$HOME\.gemini\skills"
)

$Directories = @(
    "$HOME\Documents\Learning"
    "$HOME\Documents\Jobs"
)
