#!/usr/bin/env bash
# Dotfiles manifest - single source of truth for repos, symlinks, and directories

# Repos to clone: "remote|target_path"
REPOS=(
  "git@github:MGallo-Code/EA.git|~/Documents/EA"
  "git@github:MGallo-Code/NVIM-Setup.git|~/.config/nvim"
  "git@github:MGallo-Code/Wiki.git|~/Documents/Wiki"
  "git@github:MGallo-Code/Notes.git|~/Documents/Notes"
  "git@github:MGallo-Code/IT-Worker.git|~/Documents/IT-Worker"
)

# EA-only repos (skipped with --dev)
EA_REPOS=(
  "git@github:MGallo-Code/EA.git|~/Documents/EA"
  "git@github:MGallo-Code/Wiki.git|~/Documents/Wiki"
  "git@github:MGallo-Code/Notes.git|~/Documents/Notes"
  "git@github:MGallo-Code/IT-Worker.git|~/Documents/IT-Worker"
)

# Symlinks to create: "source|target"
# Claude loads a whole DIRECTORY of rules, so a dir symlink covers every rule file.
SYMLINKS=(
  "~/Documents/EA/claude-config/global-rules|~/.claude/rules"
  "~/Documents/EA/claude-config/global-hooks|~/.claude/hooks"
)

# Combined global rules for single-file agent tools.
# Codex and Gemini each load ONE global instruction file (AGENTS.md / GEMINI.md),
# not a directory. You can't symlink a dir into a file, so we GENERATE that file by
# concatenating every global-rules/*.md - one source of truth, three consumers.
# (agent-skills.md is one of those files, so the skills nudge is still included.)
# Regenerated by setup.sh and sync.sh; never hand-edit the generated targets.
GLOBAL_RULES_DIR="~/Documents/EA/claude-config/global-rules"
COMBINED_RULES_TARGETS=(
  "~/.codex/AGENTS.md"
  "~/.gemini/GEMINI.md"
)

# Concatenate all global-rules/*.md into each single-file target. Idempotent;
# replaces a prior symlink with a generated file. Written to be safe under `set -e`.
# Relies on expand()/ok()/warn() from the sourcing script (setup.sh / sync.sh).
regen_combined_agent_rules() {
    local src; src="$(expand "$GLOBAL_RULES_DIR")"
    if [ ! -d "$src" ]; then warn "combined-rules: no global-rules dir at $src"; return 0; fi
    local tmp; tmp="$(mktemp)"
    printf '%s\n\n' "<!-- AUTO-GENERATED by dotfiles from $GLOBAL_RULES_DIR. Edit the source rule files, not this copy. -->" > "$tmp"
    local f
    for f in "$src"/*.md; do
        [ -f "$f" ] || continue
        cat "$f" >> "$tmp"
        printf '\n\n' >> "$tmp"
    done
    local tgt expanded
    for tgt in "${COMBINED_RULES_TARGETS[@]}"; do
        expanded="$(expand "$tgt")"
        mkdir -p "$(dirname "$expanded")"
        if [ -L "$expanded" ]; then rm -f "$expanded"; fi
        cp "$tmp" "$expanded"
        ok "combined-rules: generated $tgt"
    done
    rm -f "$tmp"
}

# ── Forked agent-skills (addyosmani/agent-skills) ────────────────────
# Two remotes: origin = your fork (MGallo-Code/agent-skills, trusted, push),
# upstream = Addy (untrusted source of truth, gated pull). Synced by the
# dedicated, security-gated sync_skills_repo() in sync.sh, NOT the generic
# sync_repo (which would blind ff-pull origin and skip the gate). Kept OUT of
# REPOS for that reason.
AGENT_SKILLS_DIR="~/Documents/agent-skills"
AGENT_SKILLS_UPSTREAM="https://github.com/addyosmani/agent-skills.git"

# Each tool reads global skills from its own dir; sync symlinks every
# skills/<name> from the vendor repo into each (idempotent, never clobbers
# existing real skill dirs like calendar/contact/dev-update).
AGENT_SKILLS_TARGETS=(
  "~/.claude/skills"
  "~/.codex/skills"
  "~/.gemini/skills"
)

# Directories to ensure exist
DIRECTORIES=(
  "~/Documents/Learning"
  "~/Documents/Jobs"
)

# Shell command files (relative to dotfiles repo root)
SHELL_CORE="shell/core.zsh"
SHELL_EA="shell/ea.zsh"
