# Dotfiles manifest - Windows (mirrors manifest.sh)

# ── Managed-root ROLES (mirror of manifest.sh) ───────────────────────
# Every root dotfiles manages has exactly one role: active-repo (synced, $Repos),
# archive-repo (NOT synced, $ArchivedRepos), external-managed ($AgentSkillsDir),
# generated-target (written by dotfiles), artifact-dir ($Directories). An archived root
# must NEVER appear in an active list or it resurrects stale generated affordances.
# See manifest.sh for the full taxonomy and INVARIANTS.md.

# Active managed repos (role: active-repo). Parity: must match manifest.sh REPOS.
$Repos = @(
    @{ Remote = "git@github:MGallo-Code/EA.git";         Target = "$HOME\Documents\EA" }
    @{ Remote = "git@github:MGallo-Code/NVIM-Setup.git";  Target = "$env:LOCALAPPDATA\nvim" }
    @{ Remote = "git@github:MGallo-Code/Wiki.git";        Target = "$HOME\Documents\Wiki" }
    @{ Remote = "git@github:MGallo-Code/Notes.git";       Target = "$HOME\Documents\Notes" }
)

# Archived repos (role: archive-repo). NEVER synced. Currently EMPTY: IT-Worker local copy
# removed 2026-06-19 (archive on GitHub; artifacts in Customer-Work). Parity: manifest.sh ARCHIVED_REPOS.
$ArchivedRepos = @()

# EA-only repos (skipped with --dev) - subset of active $Repos. Parity: manifest.sh EA_REPOS.
$EARepos = @(
    "EA"
    "Wiki"
    "Notes"
)

$Symlinks = @(
    @{ Source = "$HOME\Documents\EA\claude-config\global-rules"; Target = "$HOME\.claude\rules" }
    # Mirror of manifest.sh: wire the global-hooks dir so hook scripts (notify,
    # stacked-push guard) are available on Windows too. Without this, ~/.claude/hooks
    # never exists on Windows. (parity-checked: scripts/ci/check-parity.py)
    @{ Source = "$HOME\Documents\EA\claude-config\global-hooks"; Target = "$HOME\.claude\hooks" }
    # Mirror of manifest.sh: global-agents -> ~/.claude/agents (Claude subagent defs).
    # Claude-only; codex/gemini have no subagent concept. (parity-checked: scripts/ci/check-parity.py)
    @{ Source = "$HOME\Documents\EA\claude-config\global-agents"; Target = "$HOME\.claude\agents" }
)

# Codex and Gemini each load ONE global instruction file. Mirror of manifest.sh:
# instead of symlinking only agent-skills.md, GENERATE a combined file from ALL
# global-rules/*.md so Windows agents get the FULL ruleset, not a subset. Generated by
# Regen-CombinedAgentRules in setup.ps1. (parity-checked: scripts/ci/check-parity.py)
$GlobalRulesDir = "$HOME\Documents\EA\claude-config\global-rules"
$CombinedRulesTargets = @(
    "$HOME\.codex\AGENTS.md"
    "$HOME\.gemini\GEMINI.md"
)

# ── Forked agent-skills (addyosmani/agent-skills) ────────────────────
# Two remotes: origin = your fork (trusted, push), upstream = Addy (untrusted,
# gated pull). Synced by the dedicated, security-gated Sync-SkillsRepo in
# sync.ps1, NOT the generic Sync-Repo. Kept OUT of $Repos for that reason.
$AgentSkillsDir = "$HOME\Documents\agent-skills"
$AgentSkillsUpstream = "https://github.com/addyosmani/agent-skills.git"

# Each tool reads global skills from its own dir; sync symlinks every
# skills\<name> from the vendor repo into each (idempotent, never clobbers
# existing real skill dirs like calendar/contact/dev-update).
$AgentSkillsTargets = @(
    "$HOME\.claude\skills"
    "$HOME\.codex\skills"
    "$HOME\.gemini\skills"
)

# ── MCP host identity (ADR-0002 / remote-hubs, mirror of manifest.sh) ──
# The HOST is the ONE machine that runs + serves the MCP hubs (courier today; calendar/nexus as
# they are remoted) over Tailscale. Mac-only (login keychain / chat.db). Every other machine is a
# CLIENT reaching the hubs over Tailscale. "MCP host" is a ROLE keyed on $McpHost: migrating to the
# always-on Mac mini = change $McpHost + run the host bootstrap there. Windows is NEVER the host
# (no macOS login keychain), so this box is always a client; $McpHost only supplies the client URL
# here. (Was $MailHost when courier was the only remoted hub; generalized in remote-hubs Phase B.)
# (parity-checked: scripts/ci/check-parity.py)
$McpHost = "mikes-mac-mini"
$Tailnet = "tail7a0764.ts.net"
$CourierHttpPort = "8765"
$CourierRemoteUrl = "https://$McpHost.$Tailnet/mcp"
# Mandatory bearer token: ONE current-user-only file per machine, OUTSIDE any repo
# (never in git). Consumed via the COURIER_BEARER env var - NEVER passed on a command
# line. On Windows the file gets a restrictive ACL (icacls) since there is no chmod 600.
$CourierTokenFile = "$HOME\.config\courier\auth-token"

# calendar (remote-hubs Phase C): role-aware exactly like courier; Windows is always its CLIENT. Its
# OWN per-hub bearer (${CALENDAR_BEARER}) + token file, NEVER shared with courier. Port + serve/mcp
# paths are sole-sourced in hubs.json. (parity-checked: scripts/ci/check-parity.py)
$CalendarRemoteUrl = "https://$McpHost.$Tailnet/calendar/mcp"
$CalendarTokenFile = "$HOME\.config\calendar\auth-token"

# nexus (live personal data; remoted in remote-hubs Phase D): role-aware exactly like courier/calendar;
# Windows is always its CLIENT. Its OWN per-hub bearer (${NEXUS_BEARER}) + token file, NEVER shared.
# Port + serve/mcp paths are sole-sourced in hubs.json. (parity-checked: scripts/ci/check-parity.py)
$NexusRemoteUrl = "https://$McpHost.$Tailnet/nexus/mcp"
$NexusTokenFile = "$HOME\.config\nexus\auth-token"
# CUTOVER GATE (remote-hubs Phase D §0): until the coordinated nexus migration runs, nexus stays
# stdio so the live local-stdio agent + still-tracked nexus.db keep working. The Phase-D cutover flips
# this to $true (here AND in manifest.sh's NEXUS_REMOTED) in ONE coordinated step, AFTER the host seeds
# the authoritative nexus.db and serves it over HTTP - that flip turns every client into a thin
# http+bearer nexus client. Do NOT flip it before the drain (handoff §4).
$NexusRemoted = $true

# ── Custom global skills (tracked in EA), linked into all 3 agents ────
$GlobalSkillsDir = "$HOME\Documents\EA\claude-config\global-skills"

# ── Project (repo-scoped) skills -> codex/gemini, namespaced <label>-<skill> ──
# Avoids the EA/Wiki `refresh` collision. Claude keeps the project-scoped originals.
$ProjectSkills = @(
    @{ Label = "ea";        Dir = "$HOME\Documents\EA\.claude\skills" }
    @{ Label = "wiki";      Dir = "$HOME\Documents\Wiki\.claude\skills" }
    @{ Label = "sbic";      Dir = "$HOME\Documents\SBIC\.claude\skills" }
)
# Archived project skills (role: archive-project-skills). Currently EMPTY: IT-Worker skills
# removed with its local copy 2026-06-19. Parity: manifest.sh ARCHIVED_PROJECT_SKILLS.
$ArchivedProjectSkills = @()
$ProjectSkillsTargets = @(
    "$HOME\.codex\skills"
    "$HOME\.gemini\skills"
)

# ── Claude slash-commands -> codex prompts + gemini TOML ──────────────
# Source of truth stays the tracked Claude `.md`. Empty prefix = bare name.
$CommandSources = @(
    @{ Prefix = "";     Dir = "$HOME\Documents\EA\claude-config\global-commands" }
    @{ Prefix = "sbic"; Dir = "$HOME\Documents\SBIC\.claude\commands" }
)

$Directories = @(
    "$HOME\Documents\Learning"
    "$HOME\Documents\Jobs"
)

# ── Per-ROLE hub client token (shared by setup.ps1 AND sync.ps1) ──────
# Dot-sourced by both so the wiring lives in ONE place (the ADR-0002 review caught setup and sync
# each owning a copy, with the repeatable sync re-wiring courier as broken stdio). Windows is ALWAYS
# a CLIENT (no macOS login keychain) -> always the http path. GENERIC over (name, token file, bearer
# env-var) so every role-aware hub (courier + calendar) reuses it; per-hub tokens, never shared.
function Initialize-HubClientToken {
    param([string]$Name, [string]$TokenFile, [string]$BearerVar)
    $tokenDir = Split-Path $TokenFile -Parent
    New-Item -ItemType Directory -Path $tokenDir -Force | Out-Null
    # Lock the DIRECTORY down FIRST (current-user SID, inheritance removed) so a freshly written token
    # file inherits a restricted ACL - no window where it sits world/group readable (ADR-0002 review:
    # token-file perms are the highest-stakes parity divergence; there is no chmod 600 on Windows, so
    # icacls is the mechanism).
    $sid = ([Security.Principal.WindowsIdentity]::GetCurrent()).User.Value
    icacls $tokenDir /inheritance:r /grant:r "*${sid}:(OI)(CI)F" | Out-Null
    if ($LASTEXITCODE -ne 0) { Write-Warn "${Name}: icacls on $tokenDir failed (exit $LASTEXITCODE)" }

    $haveToken = (Test-Path $TokenFile) -and ((Get-Content $TokenFile -Raw -ErrorAction SilentlyContinue))
    if (-not $haveToken) {
        Write-Warn "$Name client needs the bearer token from the MCP host ($McpHost)."
        Write-Warn "On the host run:  cat $TokenFile   then paste it here."
        $sec = Read-Host "  Paste $Name token (hidden; empty to skip)" -AsSecureString
        $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec)
        $tok = [Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
        if ($tok) {
            [IO.File]::WriteAllText($TokenFile, $tok)   # no trailing newline
            Write-Ok "$Name token saved ($TokenFile)"
        }
        else {
            Write-Warn "no token entered - $Name client will 401 until $TokenFile exists."
        }
    }
    else {
        Write-Ok "$Name client token present ($TokenFile)"
    }
    if (Test-Path $TokenFile) {
        # Lock the FILE explicitly too (current-user SID), then persist <HUB>_BEARER (User scope +
        # Process) so every CLI's runtime sees it without the token ever being argv.
        icacls $TokenFile /inheritance:r /grant:r "*${sid}:F" | Out-Null
        if ($LASTEXITCODE -ne 0) { Write-Warn "${Name}: icacls on token file failed (exit $LASTEXITCODE)" }
        $tokVal = (Get-Content $TokenFile -Raw).Trim()
        if ($tokVal) {
            [Environment]::SetEnvironmentVariable($BearerVar, $tokVal, "User")
            [Environment]::SetEnvironmentVariable($BearerVar, $tokVal, "Process")
        }
    }
}

# Provision EVERY role-aware hub's client bearer in one pass (Windows is always a client). courier +
# calendar (Phase C); each its own COURIER_BEARER / CALENDAR_BEARER token + env var, never shared.
function Initialize-AllClientTokens {
    Initialize-HubClientToken "courier"  $CourierTokenFile  "COURIER_BEARER"
    Initialize-HubClientToken "calendar" $CalendarTokenFile "CALENDAR_BEARER"
    # nexus only once it is remoted (Phase-D cutover): before the flip the host is not serving nexus
    # over HTTP, so prompting a client for a nexus bearer it cannot get yet would only confuse.
    if ($NexusRemoted) { Initialize-HubClientToken "nexus" $NexusTokenFile "NEXUS_BEARER" }
}

# ── Per-ROLE hub MCP wiring (mirror of manifest.sh register_hub_mcp / register_all_hub_mcp) ──
# Phase A of the remote-hubs plan generalized the single courier function into hub primitives so
# the same per-role wiring covers EVERY hub (dotfiles INV-5, scripts/ci/check-hub-wiring.py).
# Windows is NEVER the MCP host: courier is always the http CLIENT, the rest are local stdio.

# stdio add for one hub on one CLI (local role). nexus/docgen/calendar only - courier is never
# wired stdio on Windows (always the http client; see Register-AllHubMcp). The `--` exec
# separator is cli-specific: claude/codex take it, gemini does not.
function Add-HubStdioMcp {
    param([string]$Cli, $CmdSource, [string]$Name)
    $envArgs = @(); $exec = @()
    switch ($Name) {
        "nexus"    { $exec = @("node", $NexusServer) }
        "docgen"   { $envArgs = @("--env", "PYTHONPATH=$DocgenSrc", "--env", "PLAYWRIGHT_BROWSERS_PATH=$DocgenBrowsers"); $exec = @("uv", "run", "--project", $DocgenPath, "--no-sync", "python", "-m", "docgen.server") }
        "calendar" { $envArgs = @("--env", "PYTHONPATH=$CalendarSrc"); $exec = @("uv", "run", "--project", $CalendarPath, "--no-sync", "python", "-m", "ea_calendar.server") }
    }
    switch ($Cli) {
        "claude" { & $CmdSource mcp add --scope=user $Name @envArgs -- @exec | Out-Null }
        "codex"  { & $CmdSource mcp add $Name @envArgs -- @exec | Out-Null }
        "gemini" { & $CmdSource mcp add --scope user $Name @envArgs @exec | Out-Null }
    }
}

# http client add for one hub on one CLI. GENERIC over (url, token_env). The header is built by
# SINGLE-QUOTE concatenation so the literal ${<TokenEnv>} REFERENCE (not its value) reaches the
# CLI, which stores the ref and resolves it at runtime (dotfiles INV-4). Single-quote concat
# avoids the backtick-escape fragility of an interpolated string.
# INV-4 defense: re-lock ~/.gemini/settings.json to the current user after a gemini http add, because
# gemini may MATERIALIZE the bearer reference into the file (verified on WSL/Linux). Unlike the courier
# token file - which WE create inside an already-locked dir, so it is clean by construction and needs no
# reset - settings.json is created by GEMINI and may carry a pre-existing EXPLICIT ACE. So `icacls
# /reset` FIRST strips any explicit ACE (back to inherited), THEN /inheritance:r removes inherited and
# /grant:r grants owner-only: a FULL owner lock, not best-effort. The cross-platform backstop is
# check-hub-wiring.py --host, which DETECTS a materialized literal token (not perms-gated) for ROTATION.
function Lock-GeminiSettings {
    $gset = Join-Path $HOME ".gemini\settings.json"
    if (Test-Path $gset) {
        $sid = ([Security.Principal.WindowsIdentity]::GetCurrent()).User.Value
        icacls $gset /reset | Out-Null
        icacls $gset /inheritance:r /grant:r "*${sid}:F" | Out-Null
    }
}

function Add-HubHttpMcp {
    param([string]$Cli, $CmdSource, [string]$Name, [string]$Url, [string]$TokenEnv)
    $hdr = 'Authorization: Bearer ${' + $TokenEnv + '}'  # hub-wiring-allow (audited: env-ref via single-quote concat; PS has no bash ${$var} indirection)
    switch ($Cli) {
        "claude" { & $CmdSource mcp add --scope=user --transport http $Name $Url --header $hdr | Out-Null }
        "gemini" {
            & $CmdSource mcp add --scope user --transport http -H $hdr $Name $Url | Out-Null
            Lock-GeminiSettings
        }
        "codex"  { & $CmdSource mcp add $Name --url $Url --bearer-token-env-var $TokenEnv | Out-Null }
    }
}

# Wire ONE hub for its role, for one CLI (the per-hub primitive; folds the old Register-CourierMcp).
function Register-HubMcp {
    param([string]$Cli, $CmdSource, [string]$Name, [string]$Role, [string]$Url = "", [string]$TokenEnv = "")
    switch ($Role) {
        "host"   { Add-HubStdioMcp $Cli $CmdSource $Name }
        "client" { Add-HubHttpMcp  $Cli $CmdSource $Name $Url $TokenEnv }
        default  { Write-Warn "Register-HubMcp: unknown role '$Role' for $Name" }
    }
}

# Wire ALL global hubs for one CLI - the dedup'd replacement for the Register-GlobalMcp that
# setup.ps1 and sync.ps1 each carried. Idempotent (remove-then-add). Windows is always a client,
# so courier is wired http; nexus/docgen/calendar are local stdio. EVERY hub `mcp add` lives HERE.
function Register-AllHubMcp {
    param([string]$Cli)
    $cmd = Get-Command $Cli -ErrorAction SilentlyContinue
    if (-not $cmd) { Write-Warn "$Cli not found - skipping its global MCP wiring"; return }
    if ($Cli -eq "codex") {
        # codex keeps MCP servers in config.toml; `codex mcp` can't run when that file won't parse
        # (a drifted-version entry with an invalid transport), deadlocking re-wiring. Text-strip
        # the managed blocks first so codex can always load.
        $cfg = Join-Path $HOME ".codex\config.toml"
        if (Test-Path $cfg) {
            $c = Get-Content $cfg -Raw
            $c = [regex]::Replace($c, '(?m)^\[mcp_servers\.(?:nexus|courier|docgen|calendar)(?:\.[^\]]*)?\][^\r\n]*\r?\n(?:(?!^\[)[^\r\n]*\r?\n?)*', '')
            $c = [regex]::Replace($c, '(\r?\n){3,}', "`n`n")
            Set-Content -Path $cfg -Value $c -NoNewline
        }
    } else {
        $scope = if ($Cli -eq "claude") { @("--scope=user") } else { @("--scope", "user") }
        foreach ($name in @("nexus", "courier", "docgen", "calendar")) { & $cmd.Source mcp remove @scope $name 2>$null | Out-Null }
    }
    # nexus: role-aware ONLY after the Phase-D cutover ($NexusRemoted). Until then it stays stdio so
    # the live local-stdio agent + the still-tracked nexus.db keep working (handoff §0). Windows is
    # always a client, so the flip wires it as an http+bearer client (its own per-hub token).
    if ($NexusRemoted) {
        Register-HubMcp $Cli $cmd.Source "nexus" "client" $NexusRemoteUrl "NEXUS_BEARER"
    } else {
        Register-HubMcp $Cli $cmd.Source "nexus" "host"
    }
    Register-HubMcp $Cli $cmd.Source "docgen"   "host"
    # Windows is always a client: courier + calendar over http+bearer (each its own per-hub token).
    Register-HubMcp $Cli $cmd.Source "courier"  "client" $CourierRemoteUrl  "COURIER_BEARER"
    Register-HubMcp $Cli $cmd.Source "calendar" "client" $CalendarRemoteUrl  "CALENDAR_BEARER"
    Write-Ok "$Cli`: global MCP wired (nexus + courier + docgen + calendar)"
}
