#!/usr/bin/env bash
# check-combined-rules.sh - INV-15 enforcer (bash half; PowerShell half: check-combined-rules.ps1).
#
# Hermetic: a throwaway $HOME with a small global-rules source, driven through the real
# scripts/regen-agent-rules.sh (the entrypoint EA's hooks call, which sources manifest.sh's
# regen_combined_agent_rules - the same function setup.sh/sync.sh call). Asserts:
#   - both targets are generated from every source file, identical, and read-only
#   - --quiet prints nothing when current; a write is always reported
#   - writes go through a rename (a new inode), never an in-place rewrite
#   - a stale copy (its body still matches the header checksum) is replaced without a backup
#   - every other differing copy - unlocked edit, edit that kept 0444 (sed -i, :w!), or a
#     legacy header - is warned about and saved under its own name, so no later run ever
#     overwrites an earlier backup (2026-09-10: one fixed .sync-backup slot, 0444 after the
#     first copy, silently stopped taking backups)
#   - an empty source or an unreadable rule file never replaces a real ruleset
#   - a copy that cannot be backed up is left unchanged, even when a write would succeed
# Exit 0 = all assertions hold, 1 = a regression.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
T="$(mktemp -d)"
trap 'chmod -R u+w "$T" 2>/dev/null; rm -rf "$T"' EXIT

export HOME="$T/home"
SRC="$HOME/Documents/EA/claude-config/global-rules"
CX="$HOME/.codex/AGENTS.md"
GM="$HOME/.gemini/GEMINI.md"
mkdir -p "$SRC"
printf '# Rule A\nalpha\n' > "$SRC/a.md"
printf '# Rule B\nbravo\n' > "$SRC/b.md"

fail=0
pass() { echo "  ok    $1"; }
bad()  { echo "  FAIL  $1"; fail=1; }
expect() { if "${@:2}"; then pass "$1"; else bad "$1"; fi; }
has()     { grep -qF -- "$2" "$1"; }
lacks()   { ! grep -qF -- "$2" "$1"; }
says()    { printf '%s' "$OUT" | grep -qF -- "$1"; }
never_says() { ! says "$1"; }
silent()  { [ -z "$OUT" ]; }
locked()  { [ -f "$1" ] && [ -z "$(find "$1" -prune -perm -0200)" ]; }
same()    { cmp -s "$1" "$2"; }
backups() { local n=0 b; for b in "$1".sync-backup-*; do [ -f "$b" ] && n=$((n + 1)); done; [ "$n" -eq "$2" ]; }
backed_up() { local b; for b in "$1".sync-backup-*; do [ -f "$b" ] && grep -qF -- "$2" "$b" && return 0; done; return 1; }
unlock_and_edit() { chmod u+w "$1"; printf '%s\n' "$2" >> "$1"; }
locked_edit() { unlock_and_edit "$1" "$2"; chmod 0444 "$1"; }
inode() { ls -di "$1" | awk '{print $1}'; }
regen() { OUT="$(bash "$ROOT/scripts/regen-agent-rules.sh" "$@" 2>&1)"; }

echo "check-combined-rules: fresh generate"
regen --quiet
expect "codex target has every source file" has "$CX" "alpha"
expect "codex target has every source file (2)" has "$CX" "bravo"
expect "gemini target identical to codex" same "$CX" "$GM"
expect "codex target read-only" locked "$CX"
expect "gemini target read-only" locked "$GM"
expect "a write is reported even with --quiet" says "generated"

echo "check-combined-rules: idempotent"
regen --quiet
expect "--quiet prints nothing when current" silent
regen
expect "without --quiet, reports current" says "already current"

echo "check-combined-rules: source changed (stale copy)"
printf '# Rule C\ncharlie\n' > "$SRC/c.md"
ino="$(inode "$CX")"
regen --quiet
expect "written by rename, not in place" [ "$(inode "$CX")" != "$ino" ]
expect "target picks up the new source file" has "$CX" "charlie"
expect "stale copy replaced without a backup" backups "$CX" 0
expect "stale copy is not reported as a hand-edit" never_says "did not match"
expect "target read-only again" locked "$CX"

echo "check-combined-rules: hand-edited copy, twice, then a stale regen"
unlock_and_edit "$CX" "HAND EDIT ONE"
regen --quiet
expect "first hand-edit warned" says "did not match"
expect "first hand-edit saved" backed_up "$CX" "HAND EDIT ONE"
expect "target restored from source and read-only" locked "$CX"
expect "target no longer carries the hand-edit" lacks "$CX" "HAND EDIT ONE"
unlock_and_edit "$CX" "HAND EDIT TWO"
regen --quiet
expect "second hand-edit saved under its own name" backups "$CX" 2
expect "second hand-edit saved" backed_up "$CX" "HAND EDIT TWO"
expect "first backup survives the second" backed_up "$CX" "HAND EDIT ONE"
printf '# Rule D\ndelta\n' > "$SRC/d.md"
regen --quiet
expect "a later stale regen leaves both backups" backups "$CX" 2
expect "first backup survives a stale regen" backed_up "$CX" "HAND EDIT ONE"

echo "check-combined-rules: edit that kept the read-only mode"
locked_edit "$CX" "LOCKED EDIT"
regen --quiet
expect "locked edit warned" says "did not match"
expect "locked edit saved" backed_up "$CX" "LOCKED EDIT"
expect "earlier backups untouched" backups "$CX" 3

echo "check-combined-rules: legacy header (no checksum)"
chmod u+w "$GM"
printf '<!-- AUTO-GENERATED by dotfiles from x. Edit the source rule files, not this copy. -->\n\nOLD RULES\n' > "$GM"
chmod 0444 "$GM"
regen --quiet
expect "legacy copy saved" backed_up "$GM" "OLD RULES"
expect "legacy copy regenerated" has "$GM" "delta"

echo "check-combined-rules: empty source"
mkdir "$T/aside" && mv "$SRC"/*.md "$T/aside/"
cp "$CX" "$T/before-empty"
regen --quiet
expect "empty source reported" says "no readable rule files"
expect "empty source leaves the target unchanged" same "$CX" "$T/before-empty"
mv "$T/aside"/*.md "$SRC/"

if [ "$(id -u)" != 0 ] && ! uname -s | grep -qiE "mingw|msys|cygwin"; then
    echo "check-combined-rules: unreadable rule file"
    cp "$CX" "$T/before-unreadable"
    chmod 000 "$SRC/b.md"
    regen --quiet
    chmod 0644 "$SRC/b.md"
    expect "unreadable rule file reported" says "could not read"
    expect "unreadable rule file leaves the target unchanged" same "$CX" "$T/before-unreadable"

    echo "check-combined-rules: backup impossible, write possible"
    # Unreadable but writable: the backup copy fails while a rename over it would succeed,
    # so only the fail-closed branch keeps the edit.
    unlock_and_edit "$GM" "UNSAVEABLE EDIT"
    chmod 0200 "$GM"
    regen --quiet
    chmod 0644 "$GM"
    expect "unsaveable copy reported" says "could not save"
    expect "unsaveable copy left unchanged" has "$GM" "UNSAVEABLE EDIT"
fi

if [ "$fail" -ne 0 ]; then
    echo "check-combined-rules: FAILED"
    exit 1
fi
echo "check-combined-rules OK"
