#!/usr/bin/env bash
# courier-host-bootstrap.sh  --  COURIER-HOST-BOOTSTRAP (ADR-0002)
#
# Idempotent, RE-RUNNABLE bootstrap of the courier HTTP MCP service ON THE MAIL HOST.
# Stands up everything a client needs to reach courier over Tailscale:
#   1. a mandatory bearer token (mode 600; generated once, never rotated silently),
#   2. the LaunchAgent that runs courier on 127.0.0.1:PORT in the GUI/Aqua session
#      (so himalaya can read the login keychain),
#   3. `tailscale serve` fronting it tailnet-only with TLS + a stable MagicDNS URL,
#   4. a fail-closed self-test (no-token -> 401, with-token -> not-401).
#
# Re-run it any time: token rotation (delete the file first), a plist/env change, a
# courier code update, or the Mac-mini migration (set MAIL_HOST in manifest.sh, run
# this there). It is deliberately SEPARATE from `sync` (which stays a no-daemon,
# idempotent config regen) per the ADR-0002 cross-check review: the host bootstrap is
# its OWN idempotent repair path, not a one-shot buried in a non-re-runnable setup.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"   # repo root
# shellcheck source=/dev/null
source "$SCRIPT_DIR/manifest.sh"

# Minimal helpers (this script runs standalone, not only sourced by setup.sh).
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
ok()   { echo -e "  ${GREEN}\xe2\x9c\x93${NC} $*"; }
warn() { echo -e "  ${YELLOW}!${NC} $*"; }
err()  { echo -e "  ${RED}\xe2\x9c\x97${NC} $*" >&2; }
expand() { echo "${1/#\~/$HOME}"; }

LABEL="com.ea.courier-http"
EA_PATH="$(expand "~/Documents/EA")"
COURIER_PATH="$EA_PATH/courier"
VENV_PY="$COURIER_PATH/.venv/bin/python"
TOKEN_FILE="$(expand "$COURIER_TOKEN_FILE")"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
ALLOWED_HOST="$MAIL_HOST.$TAILNET"
UID_NUM="$(id -u)"

echo "==> courier host bootstrap (MAIL_HOST=$MAIL_HOST, port $COURIER_HTTP_PORT)"

# --- 0. Sanity: must be macOS, and must actually BE the mail host -------------
# (ADR-0002 review: fail LOUD, never silently degrade a host into a client.)
if [ "$(uname -s)" != "Darwin" ]; then
    err "courier host bootstrap is macOS-only (login-keychain requirement). This is $(uname -s)."
    exit 1
fi
LOCAL_HOST_NORM="$(scutil --get LocalHostName 2>/dev/null | tr '[:upper:]' '[:lower:]')"
if [ "$LOCAL_HOST_NORM" != "$MAIL_HOST" ]; then
    err "this machine's LocalHostName ('$LOCAL_HOST_NORM') != MAIL_HOST ('$MAIL_HOST')."
    err "Refusing to bootstrap a courier host here (it would shadow the real mail host)."
    err "If this SHOULD be the mail host, set MAIL_HOST in manifest.sh to '$LOCAL_HOST_NORM'"
    err "(or fix the Local hostname in System Settings > General > Sharing), then re-run."
    exit 1
fi
if [ ! -x "$VENV_PY" ]; then
    err "courier venv python missing at $VENV_PY"
    err "run 'cd $COURIER_PATH && uv sync' first, then re-run this."
    exit 1
fi

# --- 1. Bearer token (generate once; never rotate silently) ------------------
mkdir -p "$(dirname "$TOKEN_FILE")"
chmod 700 "$(dirname "$TOKEN_FILE")" 2>/dev/null || true
if [ ! -s "$TOKEN_FILE" ]; then
    ( umask 177; openssl rand -base64 32 | tr -d '\n' > "$TOKEN_FILE" )
    chmod 600 "$TOKEN_FILE"
    ok "generated a new courier bearer token at $TOKEN_FILE (mode 600)"
    warn "to wire a CLIENT machine: run its setup and paste the value of:  cat $TOKEN_FILE"
else
    chmod 600 "$TOKEN_FILE"
    ok "courier bearer token present at $TOKEN_FILE (mode 600, kept as-is)"
fi

# --- 2. LaunchAgent plist (regenerated from manifest values every run) --------
# NOTE: interpolated paths land directly in XML <string> values, so they must be
# XML-safe (no & < >). They are here (home/venv/EA paths); guard if that ever changes.
cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- GENERATED by dotfiles/scripts/courier-host-bootstrap.sh (ADR-0002). courier HTTP MCP
     server: runs in the GUI/Aqua session so himalaya can read the login keychain; binds
     127.0.0.1:$COURIER_HTTP_PORT ONLY; the tailnet boundary is \`tailscale serve\`; auth is a
     mandatory bearer token from COURIER_AUTH_TOKEN_FILE. Re-run the script to refresh. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>$VENV_PY</string>
        <string>-u</string>
        <string>-m</string>
        <string>courier.server</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>HOME</key><string>$HOME</string>
        <key>PATH</key><string>/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
        <key>PYTHONPATH</key><string>$COURIER_PATH/src</string>
        <key>COURIER_HTTP_HOST</key><string>127.0.0.1</string>
        <key>COURIER_HTTP_PORT</key><string>$COURIER_HTTP_PORT</string>
        <key>COURIER_AUTH_TOKEN_FILE</key><string>$TOKEN_FILE</string>
        <key>COURIER_HTTP_ALLOWED_HOSTS</key><string>$ALLOWED_HOST</string>
    </dict>
    <key>WorkingDirectory</key><string>$COURIER_PATH</string>
    <key>RunAtLoad</key><true/>
    <key>KeepAlive</key><true/>
    <key>StandardOutPath</key><string>$HOME/Library/Logs/courier-http.log</string>
    <key>StandardErrorPath</key><string>$HOME/Library/Logs/courier-http.log</string>
</dict>
</plist>
PLIST_EOF
ok "wrote LaunchAgent plist $PLIST"

# --- 3. (Re)load the LaunchAgent in the GUI domain (race-safe) ----------------
# launchctl bootstrap fails with EIO(5) if it races a just-issued bootout (the old
# instance not yet fully torn down). So: bootout, WAIT for it to disappear, then
# bootstrap with a short retry, and accept "already loaded" as success (idempotent).
launchctl bootout "gui/$UID_NUM/$LABEL" 2>/dev/null || true
for _ in 1 2 3 4 5 6 7 8 9 10; do
    launchctl print "gui/$UID_NUM/$LABEL" >/dev/null 2>&1 || break
    sleep 0.5
done
boot_ok=""
for _ in 1 2 3 4 5; do
    if launchctl bootstrap "gui/$UID_NUM" "$PLIST" 2>/dev/null; then boot_ok=1; break; fi
    sleep 1
done
# If bootstrap still didn't take, a live instance already loaded is itself success.
if [ -z "$boot_ok" ] && launchctl print "gui/$UID_NUM/$LABEL" >/dev/null 2>&1; then
    boot_ok=1
fi
if [ -z "$boot_ok" ]; then
    err "launchctl bootstrap failed for $LABEL - see 'launchctl print gui/$UID_NUM/$LABEL'"
    exit 1
fi
launchctl kickstart -k "gui/$UID_NUM/$LABEL" 2>/dev/null || true
ok "courier LaunchAgent (re)loaded"

# --- 4. tailscale serve (tailnet-only TLS front) ------------------------------
TS_BIN="$(command -v tailscale || true)"
[ -n "$TS_BIN" ] || TS_BIN="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
if [ -x "$TS_BIN" ]; then
    if "$TS_BIN" serve --bg "$COURIER_HTTP_PORT" >/dev/null 2>&1; then
        ok "tailscale serve -> 127.0.0.1:$COURIER_HTTP_PORT  (https://$ALLOWED_HOST/mcp)"
    else
        warn "tailscale serve failed - check 'tailscale serve status' and that MagicDNS + HTTPS certs are enabled for the tailnet"
    fi
else
    warn "tailscale CLI not found - run by hand:  tailscale serve --bg $COURIER_HTTP_PORT"
fi

# --- 5. Fail-closed self-test (the INV-7 boundary, checked externally) --------
# courier under launchd may not be listening for a beat after kickstart, so the no-auth
# probe can transiently return 000 (connection refused). Retry until we get a REAL HTTP
# status before judging - only then is a non-401 a true failure.
# NB: the fallback must be OUTSIDE the $() - curl's -w already prints "000" on a refused
# connection, so `curl ... || echo 000` would print it TWICE ("000000") and defeat the
# "is it a real status yet?" check. Assign-on-failure avoids the double-print.
code_noauth=000
for _ in 1 2 3 4 5 6 7 8 9 10; do
    code_noauth="$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:$COURIER_HTTP_PORT/mcp" 2>/dev/null)" || code_noauth=000
    [ "$code_noauth" != "000" ] && break
    sleep 1
done
# Read the token into a mode-600 curl config so it never lands in a process argv.
tmpcfg="$(mktemp)"; chmod 600 "$tmpcfg"
printf 'header = "Authorization: Bearer %s"\n' "$(cat "$TOKEN_FILE")" > "$tmpcfg"
code_auth="$(curl -s -o /dev/null -w '%{http_code}' -K "$tmpcfg" "http://127.0.0.1:$COURIER_HTTP_PORT/mcp" 2>/dev/null)" || code_auth=000
rm -f "$tmpcfg"
if [ "$code_noauth" = "401" ] && [ "$code_auth" != "401" ] && [ "$code_auth" != "000" ]; then
    ok "self-test: no-token -> 401, with-token -> $code_auth (fail-closed gate verified)"
else
    err "self-test FAILED: no-token=$code_noauth (want 401), with-token=$code_auth (want not 401/000)."
    err "courier may still be starting - check ~/Library/Logs/courier-http.log and re-run."
    exit 1
fi
echo "==> courier host bootstrap complete."
